config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'#, as: 'helf'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login',	to:'sessions#new'
  post '/login',	to:'sessions#create'
  delete '/logout', 	to:'sessions#destroy'
  #get '/delete',		to:'messages#destroy'
  resources :users do
    member do
      get :following, :followers
      patch :block, :unblock
      resources :messages
    end
  end
  resources :microposts do
  	member do
  		patch :like, :unlike
  	end
  end
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
skip_before_action :logged_in_user
#before_action :logged_in_user, only: :home
skip_before_action :check_blocked
  def home
  	if logged_in?
	  	@micropost = current_user.microposts.build
	  	@feed_items = current_user.feed.paginate(page: params[:page])
	end
  end
  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>Sample App</h1>
<p>
  This is the about page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  This is the contact page for JP Messenger app.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Sample App</h1>
<p>
  This is the help page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
	<!--span style="float:right; background-color: lightgreen; width:135px; font-size:17px; padding:15px;">
		<%#= link_to "My Messages", messages_path %>
	</span-->
    <aside class="col-md-4">
      <section class="user_info">
	        <%= render 'shared/user_info' %>
	  </section>
	  <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <%# byebug %>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>

  </div>
<% else %>
	<div class="center jumbotron">
	  <h1>JP MESSENGER APP</h1>

	  <h2>
	    This is the home page for the
	    the demo application
	  </h2>
	  <div><%= link_to image_tag("https://seeklogo.com/images/F/facebook-messenger-logo-1B1179FB01-seeklogo.com.png", alt: "messenger logo"),
	            '#' %></div>
	  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary", style:"margin:70px" %>
	</div>

	<%#= link_to image_tag("rails.png", alt: "Rails logo"),
	            'http://rubyonrails.org/' %>
	<%#= link_to image_tag("kitten.jpg", alt: "kitten logo"),
	            'http://rubyonrails.org/' %>
	
<% end %>