config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'#, as: 'helf'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login',	to:'sessions#new'
  post '/login',	to:'sessions#create'
  delete '/logout', 	to:'sessions#destroy'
  #get '/delete',		to:'messages#destroy'
  resources :users do
    member do
      get :following, :followers
      patch :block, :unblock
      resources :messages
    end
  end
  resources :microposts do
  	member do
  		patch :like, :unlike
  	end
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
	has_many :active_relationships, class_name:  "Relationship",
	                                  foreign_key: "follower_id",
	                                  dependent:   :destroy
	has_many :passive_relationships, class_name:  "Relationship",
	                           foreign_key: "followed_id",
	                           dependent:   :destroy
	has_many :microposts, dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower	

	has_many :sent_messages, class_name: "Message", foreign_key: "sender_id", dependent: :destroy
	has_many :received_messages, class_name: "Message", foreign_key: "receiver_id", dependent: :destroy
	#has_many :messages, dependent: :destroy

	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
				format: { with: VALID_EMAL_REGEX },
				uniqueness: { case_sensitive: false }				
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # Returns the hash digest of the given string.
  acts_as_voter

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  # See "Following users" for the full implementation.
  def feed
    Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id)
  end

  def name(name_only = false)
    if !self.attributes["name"].nil?
      self.attributes["name"] + (self.admin? && !name_only ? " (Admin)" : "")
    else
      self.attributes["name"]
    end
  end

	

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :logged_in_user, except: [:index, :edit, :update, :destroy]
	skip_before_action :check_blocked, only: [:new, :create]
	before_action :correct_user,   only: [:edit, :update]
	before_action :admin_user,     only: :destroy
	def index
		@users = User.paginate(page: params[:page])
		#@messages_to_user = current_user.sent_messages.where(receiver_id: params[:receiver_id])
		#@messages_from_user = current_user.received_messages.where(sender_id: params[:receiver_id])
	end

	def show
		@user = User.find(params[:id])
		@message = current_user.sent_messages.build(receiver_id: params[:receiver_id])
		@microposts = @user.microposts.paginate(page: params[:page])
	end

	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
		  # Handle a successful save.
		  redirect_to @user
		else
		  render 'new'
		end
	end
	def block
		user = User.find(params[:id])
		user.isblocked = true
		is_saved_successfully = user.save
		if is_saved_successfully
			flash.now[:success] = "Account blocked successfully!"
		else
			flash.now[:error] = "Something went wrong. Please try again later."
		end
		redirect_back(fallback_location: users_path)
	end

	def unblock
		user = User.find(params[:id])
		user.isblocked = false
		is_saved_successfully = user.save
		if is_saved_successfully
			flash.now[:success] = "Account unblocked successfully!"
		else
			flash.now[:error] = "Something went wrong. Please try again later."
		end
		flash.now[:success] = "Account unblocked successfully!"
		redirect_back(fallback_location: users_path)
	end


	def destroy
	    User.find(params[:id]).destroy
	    flash[:success] = "User deleted"
	    redirect_to users_url
	  end
	def edit
		@user = User.find(params[:id])
	end
	
	def update
	    @user = User.find(params[:id])
	    if @user.update_attributes(user_params)
	      # Handle a successful update.
	      flash[:success] = "Profile updated"
      	  redirect_to @user
	    else
	      render 'edit'
	    end
	 end
	def following
		@title = "Following"
		@user  = User.find(params[:id])
		@users = @user.following.paginate(page: params[:page])
		render 'show_follow'
	end

	def followers
		@title = "Followers"
		@user  = User.find(params[:id])
		@users = @user.followers.paginate(page: params[:page])
		render 'show_follow'
	end

	private

	def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
	# def logged_in_user
 #      unless logged_in?
 #      	store_location
 #        flash[:danger] = "Please log in."
 #        redirect_to login_url
 #      end
 #    end
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
     end
	def user_params
	  params.require(:user).permit(:name, :email, :password,
	                               :password_confirmation)
	end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_block.html.erb
<%= link_to "block", class: 'User', method: :block, remote: true%>
  

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control', value: @user.name(true) %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unblock.html.erb
<%= link_to "unblock", class: 'User', method: :unblock, remote: true%>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<div>
	  <%= gravatar_for user, size: 50 %>
	  <%= link_to user.name, user %>
	  
	</div>
	<% if current_user.admin? && !current_user?(user) %>
		<% if user.isblocked?%> 
	  	<%#= link_to "unblock", user_unblock_path, method: :get%>
				<%= link_to "Unblock", unblock_user_path(user), method: :patch, data: { confirm: "You sure?" }, class: "btn btn-success btn-xs my-buttons" %>
	  <%else%>
	  	<%#= link_to "block", user_block_path, method: :get%>
				<%= link_to "Block", block_user_path(user), method: :patch, data: { confirm: "You sure?" }, class: "btn btn-danger btn-xs my-buttons" %>
	  <% end %>
	<%end%>
	<% if !current_user?user %>
  	<%= link_to "Messages ", messages_path(id: user.id, receiver_id: user.id), class: "btn btn-primary btn-sm my-buttons" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%#= gravatar_for @user %>
      <!-- <a href="http://gravatar.com/emails" target="_blank">Change</a> -->
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
        <div>
                <% if current_user.admin? && !current_user?(@user) %>
      <% if @user.isblocked? %>
        <%= form_for(@user, url: unblock_user_path(@user)) do |f|%>
          <%= hidden_field_tag :isblocked, true %>
          <%= f.submit "Unblock", class: "btn btn-success", style: "width: 20%", data: {confirm: "You sure?"} %>
          <% if !current_user?@user %>
            <%= link_to "Messages ", messages_path(id: @user.id, receiver_id: @user.id), class: "btn btn-primary", style:"margin:20px; padding: 4px 12px;" %>
          <% end %>
        <% end %>
      <%else%>
        <%= form_for(@user, url: block_user_path(@user)) do |f| %>
          <%= hidden_field_tag :isblocked, false %>
          <%= f.submit "Block", class: "btn btn-danger", style: "width: 20%" , data: {confirm: "You sure?"}%>
          <% if !current_user?@user %>
            <%= link_to "Messages ", messages_path(id: @user.id, receiver_id: @user.id), class: "btn btn-primary", style:"margin:20px; padding: 4px 12px;" %>
          <% end %>
          <%end%>
       <% end %>
    <% end %>
          
        </div>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
  	<%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>